### ISSUE TITLE
Space in folder path making arguments fail to execute

### ISSUE THREAD

**Issue by nmk32** [manikmagar/mule-flow-diagrams#39]
Hi Manik,

I was trying to execute tool in windows x64 machine. I happen to notice that if we have a folder path with space in it, argument fails to process. Thanks for the amazing tool. It works,if i give a folder path without a space.

>muleflowdiagrams `C:\Users\<<username>>\Documents\Mule` 4
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
Unmatched argument at index 1: '4'
Usage: muleflowdiagrams [-hV] [-d=<diagramType>] [-o=<outputFilename>]
                        [-t=<targetPath>] <sourcePath>
Create Flow diagrams from mule configuration files.
      <sourcePath>   Source directory path containing mule configuration files
  -d, --diagram=<diagramType>
                     Type of diagram to generate. Valid values: GRAPH, SEQUENCE
                       Default: GRAPH
  -h, --help         Show this help message and exit.
  -o, --out=<outputFilename>
                     Name of the output file
                       Default: mule-diagram
  -t, --target=<targetPath>
                     Output directory path to generate diagram
  -V, --version      Print version information and exit.
Copyright: 2020 Manik Magar, License: MIT
Website: https://github.com/manikmagar/mule-flow-diagrams

**Comment by manikmagar** [comment]
Thank you @nmk32 for trying it out. On any terminal/command prompts, inputs with spaces should either be escaped or enclosed with double quotes.

Could you please try it following way? 

```
muleflowdiagrams “C:\Users\<<username>>\Documents\Mule 4”
```

**Comment by nmk32** [comment]
Thanks for the inputs. Tried it and it's working. 

Closing this issue.
